INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (1, 'No.6 Collaborations Project', 2, TO_DATE('12/07/2019', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (2, 'Romance', 6, TO_DATE('01/08/2019', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (3, 'World War Joy', 4, TO_DATE('07/02/2019', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (4, 'Collage', 1, TO_DATE('29/07/2016', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (5, 'Haiz', 3, TO_DATE('07/08/2015', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (6, 'Everything', 1, TO_DATE('23/02/2017', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (7, 'Know-It-All', 1, TO_DATE('26/07/2016', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (8, 'Busted', 1, TO_DATE('13/01/2003', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (9, 'Paradise', 1, TO_DATE('12/08/2013', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (10, 'Prism', 1, TO_DATE('17/12/2013', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (11, 'Continuum', 6, TO_DATE('12/09/2006', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (12, 'Harry Styles', 4, TO_DATE('31/10/2017', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (13, 'Cowboy Bebop', 1, TO_DATE('21/05/1998', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (14, 'Beatles For Sale', 1, TO_DATE('04/12/1964', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (15, 'Hey Jude', 1, TO_DATE('26/08/1968', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (16, 'Back In Black', 3, TO_DATE('25/07/1980', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (17, 'The Black Parade', 1, TO_DATE('12/09/2006', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (18, 'Battle Born', 1, TO_DATE('23/10/2012', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (19, 'Battle Studies', 1, TO_DATE('17/11/2009', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (20, 'Help!', 1, TO_DATE('06/08/1965', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (21, 'Memories Do Not Open', 1, TO_DATE('13/01/2017', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (22, 'Slowdive', 1, TO_DATE('13/01/2017', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (23, 'Everybody Else Is Doing It, So why Can''t we?', 2, TO_DATE('23/02/1993', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (24, 'Evolve', 5, TO_DATE('08/05/2018', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (25, 'If I should Fall Behind', 1, TO_DATE('02/02/1994', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (26, 'She Is Coming', 1, TO_DATE('31/05/2019', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (27, 'One Thing Remains', 1, TO_DATE('11/10/2005', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (28, 'Sick Boy', 2, TO_DATE('16/11/2018', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (29, 'Tragic Remains', 1, TO_DATE('21/09/1995', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (30, 'Rebel Rebel', 1, TO_DATE('15/02/1974', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (31, 'Warbly Jets', 1, TO_DATE('30/11/2016', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (32, 'All Time Low', 1, TO_DATE('13/05/2016', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (33, 'Hozier', 1, TO_DATE('29/09/2015', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (34, 'John Denver', 1, TO_DATE('12/04/1971', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (35, 'Late Night Feelings', 1, TO_DATE('29/11/2018', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (36, 'Uptown Special', 1, TO_DATE('10/11/2014', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (37, 'Urban Hymn', 3, TO_DATE('16/06/1997', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (38, 'In the Name of Love', 1, TO_DATE('26/07/2016', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (39, 'Where The Light Is', 4, TO_DATE('01/07/2008', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (40, 'Inside wants out', 1, TO_DATE('09/11/1999', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (41, 'Fine Line', 2, TO_DATE('11/10/2019', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (42, 'Highway', 2, TO_DATE('24/01/2014', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (43, 'Tera Zikr', 1, TO_DATE('08/11/2017', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (44, 'The Epic Collection', 2, TO_DATE('23/08/2015', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (45, 'Queen', 2, TO_DATE('30/01/2014', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (46, 'Dear Zindagi', 1, TO_DATE('15/11/2015', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (47, 'Vizdumb', 2, TO_DATE('24/12/2014', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (48, 'Pizza', 1, TO_DATE('25/06/2014', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (49, 'Aalas ka pedh', 2, TO_DATE('09/06/2015', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (50, 'Vaaqif', 1, TO_DATE('08/05/2018', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (51, 'vaaqif', 3, TO_DATE('08/05/2018', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (52, 'Desi Kalakar', 2, TO_DATE('26/08/2014', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (53, 'Milind Gaba', 2, TO_DATE('03/03/2018', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (54, 'Ishare tere', 1, TO_DATE('05/08/2018', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (55, 'Lahore', 1, TO_DATE('16/11/2017', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (56, 'Mika Singh Songs', 2, TO_DATE('02/06/2019', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (57, 'Vida', 5, TO_DATE('12/01/2017', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (58, 'Mi Gente', 1, TO_DATE('30/06/2017', 'DD/MM/YYY'));
INSERT INTO Album(albumId, albumName, numberOfSongs, releaseDate) VALUES (59, 'Fijación Oral, Vol. 1', 5, TO_DATE('12/04/2005', 'DD/MM/YYY'));
