INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (1, 'Ed Sheeran', 'Ed Sheeran is a singer/songwriter who was born in Halifax, England but was raised in Suffolk, England. He’s known for his energetic live shows, which involve him using a loop pedal and sometimes throwing some raps in for good measure.
Ed’s success story began with him playing music in older people’s homes. He first was picked up by a record producer when busking in the USA. He performed nearly a thousand gigs and street performances before getting the recognition he deserved. Unsigned projects such as Loose Change and Songs I Wrote with Amy relied on the production of long-term collaborator Jake Gosling and signaled the start of their hugely successful musical relationship. Soon he’d made countless industry friends.
Teaming up with some of the biggest names in UK grime – Wiley, Ghetts, Jme and more – he released the No. 5 Collaborations Project in January 2011, and it reached number 46 on the UK Singles Chart. One of the songs, “Little Lady” (feat. Mikill Pane), was a fan favourite, so Ed made a more radio-friendly solo version entitled “The A Team” and the rest is history. The song now has over a million sales in the UK and two million in the US.
Picked up by Asylum/Atlantic Records, Sheeran released another single entitled “You Need Me, I Don’t Need You.” He released his debut album + in September 2011, to great critical acclaim. It topped the UK Albums Chart and has sold nearly two million copies in the UK alone.
Many successful singles, features, and an EP with Yelawolf later, Ed scored his first UK #1 with the Pharrell Williams-produced “Sing”. Then came his 7x Platinum sophomore album x, which features a slew of hugely successful singles including “Don’t”, “Thinking Out Loud” and “Bloodstream”.
After an entire year of social media silence, Sheeran announced his comeback on New Year’s Day 2017. His third album, ÷, was released in March and included the hit singles “Castle on the Hill” and “Shape of You”.
Ed Sheeran was the most streamed artist on Spotify in 2017 with 47 million monthly listeners. His album, ÷, was the most streamed album in the world with 3,1 billion streams and the song “Shape of You” is the most streamed song ever with more than 1,4 billion streams.
Sheeran largely spent 2018 and the first half of 2019 on tour, but he also found time to work on his next album. It was released in July of 2019 and was titled No.6 Collaborations Project.', 1);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (2, 'Camila Cabello', 'Karla Camila Cabello Estrabao is a Cuban-American singer born on March 3, 1997, in Cojímar, Havana, Cuba. For the first five years of her life, Cabello lived in Cuba and Mexico before relocating to Miami, Florida. Cabello dropped out of her 2012/13 high school year to pursue a career in singing (although she did receive her diploma). For her quinceanera, Camila asked her parents to drive her to North Carolina, so she could audition for the second season of The X Factor US. Barely making it into the competition, she was granted an “alternate” role who was only able to audition if they had time. Eventually, she along with Dinah Jane Hansen, Ally Brooke Hernandez, Lauren Jauregui and Normani Kordei were tapped to form multi-platinum girl group, Fifth Harmony. The collective  released many chart-toppers with the highest being “Work From Home” peaking at number 4 on the Billboard Hot 100.
During this time, Cabello collaborated with Canadian artist Shawn Mendes on “I Know What You Did Last Summer,” as well as American rapper Machine Gun Kelly on “Bad Things,” which peaked at number 4 on the Billboard Hot 100.
She remained part of the group until the 19th of December 2016, where the four remaining members announced via their official Twitter account that Camila had decided to leave the group to pursue a solo career. Camila then confirmed this by posting a statement on her Twitter account.
After the split, Camila released pop and dance-influenced debut single, “Crying in The Club” on May 19, 2017 and promotional single, “I Have Questions” two days later. The first 6 months of being a solo also allowed for features to occur: with Cashmere Cat’s “Love Incredible,” J Balvin and Pitbull’s “Hey Ma,” and Major Lazer’s “Know No Better” along with American rappers Travis Scott and Quavo.
On July 20th, 2017 Cabello supported the North American leg of Bruno Mars’s “24K Magic World Tour.” Shortly after on August 4th, she released her “summer double features” “OMG” featuring Quavo, and her solo breakout hit, “Havana” featuring Young Thug. “Havana” was confirmed as a single from her self-titled debut album on August 30th, 2017 via Twitter. The song became a commercial and major success becoming her first #1 hit. The track was certified 5x platinum along with diamond certifications in Brazil and France—making Camila the fastest female artist born in the 90s to achieve a diamond certification, doing so in only 5 months.
On December 4th, 2017, Camila had revealed she changed the title of her debut album from The Hurting, The Healing, The Loving. to Camila. Alongside that announcement, two singles from her album were released; “Real Friends” and “Never Be the Same” on December 7th. The following week “Crown,” a collaboration with Grey for Netflix’s Bright was dropped.
January 12, 2018, marked the release of her solo debut project. Camila debuted at #1 in 100 different countries on iTunes, breaking the record for most #1’s for a debut album. Camila also reached a major milestone on January 21, debuting at #1 on the Billboard 200 Albums chart. Later on April 12, 2018, the album was certified platinum.
2018 saw a few more collaborations for Cabello, starting with the remix of her own hit “Never Be The Same” featuring country singer Kane Brown. “Sangria Wine” with Pharrell, who had worked on “Havana” with Cabello followed, released May 18th. The final three tracks from Cabello in 2018 were all remixes. Bazzi’s “Beautiful;” Cabello’s “Real Friends” featuring Swae Lee and an orchestral version of “Consequences” from Camila.
In January of  2019, shortly after her debut’s anniversary, Camila revealed that she began writing for her second album. On June 3, 2019, she posted an Instagram story of a Dropbox folder named CC2, suggesting she had completed the album.
A few days prior to this, Camila was featured on Mark Ronson’s track “Find U Again.” Later that month, Camila combined forces with Shawn Mendes once again to create “Señorita” which was accompanied by a steamy music video.
Camila’s second album was announced in conjunction with the released of two singles, “Shameless” and “Liar.” Within the next five weeks, Camila released two more singles, “Cry for Me” and “Easy”, which she performed live during her Saturday Night Live debut on October 12, 2019.
On November 13, 2019, Camila revealed the release date and album art for Romance, announcing that another single, “Living Proof” would be released later that week.', 2);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (3, 'Cardi B', 'Born on October 11, 1992, and raised in The Bronx, New York, Belcalis Almanzar—under the stage name Cardi B—is a rapper and TV personality known for her friendly attitude. From 2015 to 2017 she starred on the TV show Love & Hip Hop, on which she landed a role after she became popular on the internet due to her personality and stripping endeavors. Following her departure from the series, she attained success in music with her chart-topping summer smash “Bodak Yellow.” She is married to Migos member Offset. Cardi also gave birth to Kulture Kiari Cephus, Offset’s fourth child and Cardi’s first.
Cardi began her music career in 2015 and released two installments of her Gangsta Bitch Music mixtapes series up until January 2017. The tapes went by relatively quietly but caught the attention of Atlantic Records, where Cardi inked a deal in February of 2017. Shortly after, Cardi proved her worth when she entered the mainstream music scene with the release of her smash single “Bodak Yellow” on June 16, 2017. The single obtained the top spot on the Billboard Hot 100, which marked the first time a female rapper achieved this since Lauryn Hill did the same with “Doo Wop (That Thing)” in 1999. “Bodak Yellow” was certified 5x Multi-Platinum by the RIAA on February 28, 2018, for selling 5 million units in the US.
Speculations of a relationship between Cardi B and Offset arose in early 2017 after the two were repeatedly sighted together. On October 29, 2017, Offset proposed to Cardi on stage at a Philadelphia show. They have collaborated on what was at one point Cardi’s most popular single, “Lick,” Migos'' “MotorSport,” “Um Yea,” and “Drip.”
Following her engagement and the success of “Bodak Yellow,” Cardi released the follow-up single “Bartier Cardi” featuring 21 Savage just in time for Christmas. Cardi followed that up with features on the Multi-Platinum singles “No Limit” with G-Eazy and A$AP Rocky, and “Finesse (Remix)” with Bruno Mars. Cardi released her debut album, Invasion of Privacy, on April 6, 2018.
On January 2nd, 2018, Cardi B became the third artist (and first rapper) to have her first three Billboard Hot 100 entries (“Bodak Yellow,” “No Limit,” and “MotorSport”) in the chart’s top 10 simultaneously, joining only The Beatles and Ashanti in achieving the feat.
She also became the first female rapper in history to achieve three #1 singles on the Billboard Hot 100.', 3);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (4, 'Shawn Mendes', 'Shawn Peter Raul Mendes (born August 8, 1998 in Toronto, Ontario) is a Canadian singer and songwriter. He spent his early days learning to play guitar by watching YouTube tutorial videos and gained millions of followers in a few months for singing on Vine in 2013, becoming the third most-followed artist on the platform in 2014.
He officially signed with Island Records in May 2014 and released his first single “Life of the Party” on June 26, 2014. His debut album Handwritten, which included hit single “Stitches”, reached the top 10 in the U.S. and Canada, and number one in the UK. He went to re-release that album under Handwritten Revisted with four new tracks, including collaboration with Fifth Harmony member Camila Cabello, “I Know What You Did Last Summer.”
His second studio album Illuminate delivered three hit singles: “Treat You Better”, “Mercy”, and “There’s Nothing Holdin'' Me Back”. The latter single peaked in the Billboard Top 10 and also reached number one on the Mainstream Top 40 airplay chart. In August 2017, he became the first artist under 20 to have three number-one songs on the Billboard Adult Pop Songs chart.
On March 22, 2018, Mendes released “In My Blood,” the lead single from his eponymous third album, Shawn Mendes, which released on May 25, 2018. He also released the second single from the album, “Lost in Japan”, the following day on March 23.
On May 3, 2019, Mendes released “If I Can’t Have You,” which was the lead single from his highly anticipated fourth album. He teamed up with Camila Cabello to release their second single together, “Señorita”.', 4);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (5, 'The Chainsmokers', 'The Chainsmokers are a New York City-based duo consisting of Andrew Taggart and Alex Pall. They write and produce their songs, and often feature guest vocalists.
The duo rose to fame with their 2014 viral hit, “#Selfie.” The Chainsmokers broke into the mainstream with their hit song “Roses” and their debut EP Bouquet.
In a March 2016 YouTube video, the duo talked about plans to release songs featuring their vocals. This was proven when “Closer” was released on July 2016 with Andrew Taggart as co-vocalist, alongside American singer-songwriter Halsey. “Closer” became both The Chainsmokers and Halsey’s most famous song.
2016 proved to be a breakout year for The Chainsmokers, with original songs “Don’t Let Me Down” and “Closer,” both certified platinum and headlining their sophomore EP Collage. The duo finished off their most successful year yet with three GRAMMY nominations, winning one GRAMMY for Best Dance Recording for “Don’t Let Me Down.”
Following their first GRAMMY win, the duo announced their debut LP, Memories…Do Not Open, on February 12, 2017 in a red carpet interview with Entertainment Weekly. The album was released on April 7, 2017, and was followed by a US tour titled “Memories: Do Not Open.”
The duo achieved further commercial success in 2017, with the releases of “Paris” and “Something Just Like This” helping The Chainsmokers tie The Beatles and the Bee Gees with three simultaneous songs on the Billboard Hot 100’s Top 10.
After going on a hiatus of releasing songs, the duo returned in January 2018 with the release of “Sick Boy”, the first single from their second album of the same name. The Chainsmokers'' plan to build an album by releasing a song roughly every month was detailed in a Billboard article. The album spawned the minor hits of “This Feeling”, “Sick Boy”, “Side Effects”, and “Everybody Hates Me” which peaked at numbers 50, 65, 66, and 100, respectively, on the Billboard Hot 100.
The duo wasted no time in announcing their third album, World War Joy, along with their second arena tour set for the Fall of 2019. The first single off the album, “Who Do You Love” with Australian pop-rock group 5 Seconds of Summer became an instant hit, rising up the charts and currently peaking at the number 54 position.', 5);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (6, '5 Seconds of Summer', '5 Seconds Of Summer is an Australian pop-punk band composed of Luke Hemmings, Calum Hood, Ashton Irwin, and Michael Clifford. They formed in 2011 and rose to international fame when One Direction found their covers of songs on YouTube in 2013. Shortly afterwards, they released their award winning single “She Looks So Perfect.”
Their first EP, Somewhere New, was released December 7th, 2012, and featured “Unpredictable,” “Out of My Limit,” “Beside You,” and “Gotta Get Out”.
The band’s self-titled debut studio album was released June 27th, 2014. “She Looks So Perfect,” “Don’t Stop,” “Amnesia,” and “Good Girls” were released as singles, each earning a music video. “Beside You” was remastered and put on the album.
Their sophomore album, Sounds Good Feels Good, came out on October 23rd, 2015. The album was preceded by lead single “She’s Kinda Hot,” which gave fans a preview of the band’s new pop punk sound.
In early 2018, they broadcasted their new sound and released two singles, “Want You Back” and “Youngblood” in preparation for their third album. They released their third studio album Youngblood on June 15th, 2018, topping charts worldwide within hours of its release.
In May 2019, 5SOS debuted “Easier,” the first offering from their upcoming fourth studio album. On August 23, they released “Teeth” as the second single from the album.', 6);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (7, 'Halsey', 'Halsey is the stage name of New Jersey native Ashley Nicolette Frangipane. It is an anagram of her first name and reference to the Halsey Street subway stop and street in Brooklyn where she used to live. On her website, Halsey’s bio reads: “I am Halsey. I will never be anything but honest. I write songs about sex and being sad.”
With over 14,000 friends on MySpace as a tween, she began posting covers of songs on YouTube. In 2012, she posted “The Haylor Song”, a parody of Taylor Swift’s hit song “I Knew You Were Trouble” that created controversy over the nature of the lyrics. Nevertheless, she had accumulated a respectable amount of online attention, reaching 16,000 subscribers on YouTube at the age of 18.
Halsey posted her first single “Ghost” on Soundcloud in 2014, which turned heads in her direction. Her close friend Anthony pretended to be her manager, accompanying her in various meetings with different record labels. After being signed to Astralwerks, she released her EP Room 93 in late 2014, with four of the five tracks carrying accompanying music videos, giving the EP a “visual” feel. She was the most mentioned artist online at SXSW 2015, which was evident by her ever-increasing fanbase. She reached over half a million followers on Twitter at the age of 20.
In anticipation of her debut effort, Badlands, “Hold Me Down” was released as a pre-order single, followed by “New Americana”, the anthem of today’s diversified generation. Badlands was officially released on August 28th, 2015, described by Halsey as “an angry female record”. It also represents her mental state. At Firefly Music Festival 2015, she told an interviewer, “For me, it was about creating a universe and making it so that people felt like they were actually being transported somewhere.”
Halsey and Justin Bieber got together on the Skrillex-produced track “The Feeling”, which they performed together on the TODAY Show in promotion for Bieber’s fourth album Purpose. In 2016, she collaborated The Chainsmokers on the song of the summer, “Closer”, her biggest hit to date. The Grammy-nominated earworm maintained its reign at the top of the Billboard Hot 100 for 12 consecutive weeks. Halsey later dropped “Not Afraid Anymore” for the Fifty Shades Darker soundtrack.
In 2017, Halsey officially announced her sophomore album, hopeless fountain kingdom. Released on June 2nd, 2017, the record’s title fulfills the long-debated acronym “hfk” that Halsey has continuously hinted throughout the years. The album is inspired by the story of Romeo + Juliet. That same year, Halsey and then-boyfriend G-Eazy released “Him & I”
Halsey’s first track of 2018 was a feature on Thirty Seconds to Mars'' “Love Is Madness.” Collaborative track “Eastside” saw her combining forces with Khalid and benny blanco. Following this, Halsey released her first single from her unannounced 2020 album, titled “Without Me”. Following this release, Halsey and G-Eazy ended their on-again off-again relationship.
After a remix of “Without Me” by Juice WRLD was dropped,  Halsey’s 2019 began with a collaboration with English rocker YUNGBLUD titled “11 Minutes,” The pair confirmed they were dating not long after. The duo went on to sing a cover of Death Cab for Cutie’s “I Will Follow You into the Dark” for triple J.
After years of friendship, Korean-pop group BTS  featured Halsey in single “Boy With Luv” which broke many records, with the most notable being the 78 million views the music video gained in 24 hours on Youtube.
On May 17, 2019, Halsey released stand-alone single, “Nightmare,” initially intended to be the first single of Manic.
Following this, “Graveyard” was released, with Halsey and announcing that her third album Manic, would be released in January 2020.', 7);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (8, 'Justin Bieber', 'Justin Bieber (born March 1, 1994) is a pop musician and recording artist, singer-songwriter and part-time actor. Since bursting onto the scene in 2008 (after being discovered on YouTube) he has taken the world by storm and divided opinion; selling 15 million albums worldwide, making two concert-documentaries, winning numerous awards, amassing 100 million Twitter followers, and being the most Googled person on Earth more than once.
On November 17, 2009, shortly after being discovered by Usher, Bieber released his first EP, My World. The project featured his first hit “One Time.” Bieber followed with his first album, My World 2.0, on March 19, 2010. The album contained the hit “Baby,” which was famously the most disliked video on YouTube until December 2017.
Before finishing his third studio album, Justin released a Christmas album on November 1, 2011. Believe was released on June 15, 2012, and featured elements of dance and R&B music, unlike the teen-pop style of his previous works. The album included the international hits “Boyfriend,” “As Long as You Love Me” featuring Big Sean, and “Beauty and a Beat” with Nicki Minaj.
After his third album, and before his fourth, Bieber released the compilation album Journals.
His fourth full album Purpose was released on November 13, 2015, and the lead single “What Do You Mean” hit number one on the Hot 100. Surprisingly, it was his first number one hit. He later followed it up with two more number ones, “Sorry” and “Love Yourself,” which cemented his success in the adult pop world.
“Love Yourself” managed to set a record for most weeks in the top ten after debuting in the top ten, breaking out of a multiple-way tie that included the likes of “Starships” by Nicki Minaj and his own “What Do You Mean” and “Sorry.”
He was notably in a relationship with Selena Gomez between 2010 and 2013.  Since 2013, Justin Bieber and Selena Gomez dated on and off, before breaking up in March 2018. In July 2018, Bieber became engaged and later married to model Hailey Baldwin.', 8);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (9, 'Hailee Steinfeld', 'Hailee Steinfeld (born December 11, 1996) is an American actress, model and singer.
She is known for her portrayal of Mattie Ross in the 2010 film True Grit, for which she was nominated for an Academy Award for Best Supporting Actress, a Screen Actors Guild Award for Outstanding Performance by a Female Actor in a Supporting Role, and a BAFTA Award for Best Actress in a Leading Role.
Steinfeld had been “experimenting” with music since about age 12. In 2015 she got the opportunity to play some of her songs for a representative from Republic Records at an event in New York City. Four months later she signed with the label.
In May 2015, Steinfeld released a full-length cover version of the Jessie J song “Flashlight”, which she sang for Pitch Perfect 2. When a Republic Records executive announced in May that Steinfeld had signed a record deal and was working on her first release, he said, “she has the vision, natural talent and dedication to compete at the highest level.”
In July 2015, Steinfeld and singer Shawn Mendes released an acoustic version of Mendes'' single, “Stitches”. The following month, Steinfeld released “Love Myself”.
Her upcoming album is produced by Mattman & Robin and features co-writers Julia Michaels and Justin Tranter. Steinfeld said she “can’t wait” for people to hear it. “There are a lot of songs on this album that will surprise people.”', 9);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (10, 'DNCE', 'In 2015, Joe Jonas announced his first project since the Jonas Brothers officially split: a band called DNCE. Joe recruited guitarist JinJoo Lee, bassist and keyboardist Cole Whittle, and drummer Jack Lawless, who worked with Joe back in his JB days.
JinJoo told Interview Magazine the meaning of the band’s name.
‘DNCE’ is ‘dance’ without an A. It’s not a perfect word, and you don’t have to be a perfect dancer to dance. Life is just sometimes not perfect.
On September 14, 2015, the band premiered their debut single, “Cake By the Ocean,” on New York’s Z100. The song blew up and soon found a place in the background of an AT&T commercial. This drove more people to check out their music and boosted sales and popularity.
On October 23rd, 2015, the SWAAY EP was released, and a few months later the band announced they would be touring with Selena Gomez in the summer of 2016.', 10);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (11, 'Grey', 'Grey is an American electronic music duo consisting of brothers Kyle and Michael Trewartha. They are best known for their debut single “Starving”, a collaboration with American actress and singer Hailee Steinfeld, featuring production work from Russian-German DJ Zedd. Kyle Trewartha was formerly known as Singularity, under which name he released numerous remixes and original tracks to SoundCloud', 11);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (12, 'Zedd', 'Anton Zaslavski, aka. Zedd, is a Russian-German DJ and producer from Kaiserslautern, Germany.
His musical career started by playing drums in his brother’s metal band, Dioramic. After sending Skrillex a message and a demo on social media, his career as a producer and DJ started.
Making his mark on the scene by signing his first big single “Shave It Up” to Skrillex’s label OWSLA in 2011, Anton Zaslavski rose to prominence in late 2012 with his debut album Clarity and its title track featuring English singer Foxes. The song was awarded with a Grammy Award for the Best Dance Recording.
Zedd has gone on to collaborate with the likes of Lady Gaga, Ariana Grande and Justin Bieber and made an impact on the pop world.
In 2015 Zedd released his second studio album, True Colors, which further implemented his spot in both the pop and electronic realms of music. It featured the top 20 lead single “I Want You To Know” featuring Selena Gomez.
2017 saw the release of smash single “Stay” with Alessia Cara, before the release of two more singles “Get Low” with Liam Payne, which saw less success. The succeeding release of “The Middle” with Grey and Maren Morris saw extreme success on the Hot 100, becoming his fourth top 10 single in the U.S.', 12);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (13, 'Alessia Cara', 'Alessia Caracciolo is a singer-songwriter from Brampton, Ontario, Canada. Upon the release of her first single, “Here”, she shortened her last name because it was “so long and spelled crazy.”
Cara started posting covers on her YouTube channel at the age of 13. She first started to gain popularity when she posted a cover of Justin Timberlake’s “Mirrors.” Soon after, her cover of The Neighbourhood’s “Sweater Weather” took off. These covers got her signed to EP Entertainment and later, Def Jam.
Her first single, “Here” premiered on The FADER on April 27th, 2015, and blew up soon after. Just four months later, the song racked up 18 million Spotify streams in addition to 4.5 million views on its official video.
On August 26th, 2015, Cara leaked her first EP, titled Four Pink Walls. Each song, including “Here”, was accompanied by a video.
Her debut album, Know-It-All released on November 13, 2015.
Cara won the Grammy Award for Best New Artist at the 2018 Grammys held on Jan. 28, 2018.
She released her second studio album, The Pains of Growing, on November 30, 2018. The album discusses, in part, many of the changes Cara’s life underwent after achieving fame and becoming an adult. It was supported by the singles “Growing Pains” and “Trust My Lonely,” and earned critical praise.', 13);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (14, 'Busted', 'Busted is an British pop-rock, pop-punk band composed of Charlie Simpson, James Bourne and Matt Wills, formed in 2000. Willis claimed that they had been inspired by Green Day, Blink-182 and BBMak. Busted have sold over 5 million albums worldwide.
The band had four UK number-one singles, released two studio albums, Busted (2002) and A Present for Everyone (2003), one compilation album and one live album before breaking up in January 2005 following Simpson’s decision to pursue a career fronting post-hardcore band Fightstar. They have also won two Brit Awards and won The Record of the Year in 2004 with their single “Thunderbirds”, amongst other awards.
During their break-up, each member pursued solo careers: Charlie Simpson worked with the previously mentioned Fightstar, Matt Willis released his album Don’t Let It Go to Waste in 2006 and worked in TV, and James Bourne formed Son of Dork and worked under the name Future Boy in a solo electronic project.
In 2013, after appearing as guests in McFly’s 10-year anniversary concerts, James and Matt, along with McFly, formed supergroup McBusted, releasing a self-titled album and touring. During this period, James and Matt got in contact with Charlie to let him know of McBusted, and discussed the possibility of making music together again.
On 3 May 2016, Busted released their first new song in 12 years, “Coming Home”, as a free download, and later released their third album Night Driver.', 14);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (15, 'John Mayer', 'John Clayton Mayer, born October 16, 1977, is a singer-songwriter and guitarist whose work has spanned many genres over the course of his career. Raised in Fairfield, Connecticut, he attended the prestigious Berklee College of Music, hoping to refine his guitar skills. He dropped out after one year to pursue his career.
After striking a deal with Aware/Columbia Records, he released his debut album, Room for Squares in 2001. The single “Your Body Is a Wonderland” launched him to fame, winning him a Grammy Award for Best Male Pop Vocal Performance in 2003. That same year, he released his second album Heavier Things, spawning the single “Daughters”, which won Song of the Year in 2005.
After performing soft rock/pop in his early career, he began moving towards the blues genre that had initially influenced him as a musician, collaborating with B.B. King and Eric Clapton among others. In 2005, he formed the blues group John Mayer Trio, releasing Try! that same year. Mayer’s 2006 album Continuum continued his foray into the blues genre and won him Grammy for Best Pop Vocal Album in 2007, producing the hit singles “Waiting on the World to Change” and “Gravity”.
His 2009 album Battle Studies saw a return to pop rock and a number-one grossing world tour. Mayer withdrew from public life in 2010 after controversial interviews with Playboy and Rolling Stone and began work on his fifth studio album Born and Raised, released in 2012. The album is a shift in sound for Mayer, incorporating folk and country rock. A granuloma on his vocal chords delayed the release of the album and cancelled the subsequent tour.
In 2013, John released Paradise Valley and during a concert in Adelaide, he covered the Beyoncé song “XO” and one month later, he released a studio version of the song. In August 2015, Mayer and the Grateful Dead formed the group Dead & Company, along with Jeff Chimenti and Oteil Burbridge and they began a tour in the US that continued in 2016. In November of the same year, John released the lead single “Love on the Weekend” of his seventh studio album The Search For Everything, out in 2017.', 15);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (16, 'Katy Perry', 'Katheryn Elizabeth “Katy” Hudson (born October 25, 1984), known by her stage name Katy Perry, is an American singer, songwriter, businesswoman, philanthropist, and actress. She was born and raised in Santa Barbara, California. Having had very little exposure to mainstream pop music in her childhood, she pursued a career in gospel music as a teen and released her debut self-titled studio album in 2001. She also recorded a second solo album in 2005, (A) Katy Perry, which was scrapped.
Afterwards, Perry (her mother’s maiden name, taken to avert confusion with Kate Hudson) reinvented herself  as a party girl pop star,  breaking out with 2008’s One of the Boys and the #1 hits “I Kissed a Girl” and “Hot n Cold”.
Follow-up Teenage Dream (2010) equalled Michael Jackson’s record of five chart-toppers on the same album, and made Perry even more ubiquotous in the pop landscape. Following her marriage and eventual divorce from British comedian Russell Brand, she released an updated version, Teenage Dream: The Complete Confection and concert film Katy Perry: Part of Me in 2012. She released her fourth album, Prism, in 2013, along with some standalone singles, such as “Rise”.
In 2017 Katy began promoting her fourth Album by releasing the Skip Marley collaboration “Chained to the Rythm” on February 10 and performing it live at the 2017 Brit Awards 12 days later. Two singles “Bon Appétit” featuring Migos and “Swish Swish” featuring Nicki Minaj followed before the release of the album. Titled Witness, Katy’s fifth LP (fourth under her current name) debuted at #1 on the Billboard #200, marking her third #1 in the U.S.', 16);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (17, 'Juicy J', 'Jordan Michael Houston (born April 5, 1975), better known by his stage name Juicy J, is an American rapper, record producer and Academy Award-winning songwriter.
Juicy is a founding member of the hip-hop group Three 6 Mafia, and is currently signed to Wiz Khalifa’s Taylor Gang Records.', 17);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (18, 'Harry Styles', 'Harry Edward Styles is a widely-recognized singer, songwriter, and actor whose career continues to set records. Upon auditioning for the singing competition show “The X Factor” in 2010 at only sixteen years old, he and four other young men who tried out to be solo artists were joined together to form the platinum-selling, globally renowned band known as One Direction. Harry is credited with writing songs for Ariana Grande, Meghan Trainor, One Direction, himself, and more.
His debut solo single “Sign Of The Times” was released on April 7, 2017, in advance of its album accompaniment, and was greeted with great excitement as the song landed in the number one spot on the charts in over twenty countries.
Harry’s self-titled debut album was released on May 12, 2017 and immediately shot to the top of the charts, landing in the number one position in 84 different countries along with selling a historic 230,000 album units. This was record breaking, and Harry now holds the title for the biggest debut sales week for a British male musician in the United States.
Two weeks before the release of his album, Harry announced that tickets for a small-venue world tour would be going on sale via his Twitter account. Seven days before the world had heard the entirety of his album, Styles’ world tour sold out every single concert location in under two minutes.
Harry’s debut professional acting role came as Alex in Academy-Award Nominee Christopher Nolan’s Dunkirk, released July 21, 2017.', 18);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (19, 'Cowboy Bebop', '', 19);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (20, 'The Beatles', 'The Beatles are arguably the most famous, critically-acclaimed, and successful rock band of all time—certainly the preeminent group of the 20th century. They started out as four teenagers playing grimy basement clubs in Liverpool and Hamburg, but they progressed to become world-beating rock stars who are still influential to this day.
John Lennon first formed a skiffle group called The Quarrymen in March 1957. A fifteen-year-old Paul McCartney joined shortly thereafter, eventually inviting his friend George Harrison to audition for the band. After finally impressing John with his guitar skills, George was asked to join—but this juncture would be short-lived as John’s departure to college signaled the other quarrymen to go their separate ways.
By 1960, Lennon, McCartney, and Harrison had re-branded from ‘Johnny & the Moondogs’ to ‘The Silver Beetles’ at the behest of their new bass player, Stuart Sutcliffe. The name would eventually evolve into ‘The Silver Beatles’ by July of that year, before settling on ‘The Beatles’ come August—just in time for their trip to Hamburg with new drummer, Pete Best. Though club residencies in Germany would prove fundamental to the group’s progress as a whole, the tour turned out to be a blessing and a curse, following the deportation of a then-seventeen-year-old George Harrison, and the eventual tragic death of Stuart Sutcliffe.
Upon returning to Liverpool and regrouping, they would develop an ongoing relationship with local record store owner Brian Epstein, beginning in late 1961; eventually signing a five-year contract with him in January of 1962. After securing a record deal with George Martin at Parlophone, Ringo Starr would be asked to replace Best on the drums.
After five years and ten thousand hours of practice, the classic Beatles lineup had finally come to fruition:


Lennon
(rhythm guitar/vocals)

McCartney (bass/vocals)

Harrison (lead guitar/vocals)

Starr (drums/percussion)

Early singles, particularly “She Loves You,” quickly earned them an enormous, passionate following. Beatlemania was officially sparked by the time of their October 13, 1963 performance at the London Palladium.
They capitalized on this phenomenon by touring extensively, and releasing five albums in little over two years. Lennon and McCartney developed a fruitful songwriting partnership, which inspired The Byrds, The Rolling Stones, and The Who to write their own songs. Lennon was writing increasingly intricate lyrics with the aim of matching Bob Dylan’s abilities, while McCartney’s own rivalry with Brian Wilson of The Beach Boys pushed the band in new sonic directions. Resenting his marginalization, Harrison began writing songs of his own, which reflected his mystic interests.
By August 1966, they grew weary of touring, deciding to focus their energies on creating much more complex music in the studio. In successive years, they released Revolver and Sgt Pepper’s Lonely Hearts Club Band, followed by the untimely death of beloved manager Brian Epstein in 1967. They proceeded with the movie and accompanying soundtrack, Magical Mystery Tour, in December of that same year, before taking another hiatus to study transcendental meditation with the Mahirishi Mahesh Yogi in India. They returned with The Beatles—also known as the White Album—and Abbey Road, followed by Let It Be. Individually, these are among the greatest albums ever recorded; together, they form a discography beyond compare.
Highlights of their catalogue include:

Lennon-penned: “I Am The Walrus”, “Strawberry Fields Forever”, “Across The Universe”

McCartney-penned: “Let It Be”, “Hey Jude”, “For No One” and the most covered song of all time, “Yesterday”.
Harrison-penned: “Something”, “While My Guitar Gently Weeps”, “Here Comes The Sun”.

While Ringo only contributed three writing credits (“What Goes On”, “Don’t Pass Me By”, and “Octopus’s Garden”), he has a lead vocal track on almost every album the band released.
All four members had successful solo careers. Lennon was one of the foremost musicians of the early 1970s, and Harrison’s All Things Must Pass is considered to be a masterpiece. McCartney was the most commercially successful; his albums continued to sell in high volumes well into the 1980s, and his tours remain phenomenally popular. Starr had the most irregular career, but, since 1989, joins together with various rock veterans in the supergroup known as Ringo Starr And His All-Starr Band.', 20);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (21, 'ACDC', 'AC/DC is an Australian rock band, formed in 1973 by brothers Malcolm and Angus Young, who have remained the sole constant members (though Malcolm left prior to the recording of 2015’s Rock or Bust due to medical issues). Commonly classified as hard rock, they are considered pioneers of heavy metal and are sometimes classified as such, though they themselves have always classified their music as simply “rock and roll”. To date, they are one of the highest grossing bands of all time.
But when their vocalist, Bon Scott died after a night out in London, the group wanted to disband. That didn’t happen. Instead, Scott was replaced with Brian Johnson. Their only statement to Scott’s Death was that he had “drunken himself to Death.”
Malcolm and Angus Young came up with the band name after their sister saw “AC/DC” on the side of an electric sewing machine, and ended up asking, “Why not AC/DC?”
As of 2010, AC/DC had sold more than 200 million albums worldwide, including 71 million albums in the United States alone. 1980’s Back in Black, the first album with singer Brian Johnson, has sold an estimated 49 million units worldwide, making it the third highest-selling album by any artist, and the second highest-selling album by any band, behind Pink Floyd’s Dark Side of The Moon and Michael Jackson’s Thriller. The album has sold 22 million units in the U.S. alone, where it is the fifth-highest-selling album of all-time. AC/DC ranked fourth on VH1’s list of the “100 Greatest Artists of Hard Rock” and was named the seventh “Greatest Heavy Metal Band of All Time” by MTV. In 2004, AC/DC was ranked number 72 in the Rolling Stone list of the “100 Greatest Artists of All Time”. In 2010, AC/DC were ranked number 23 on the VH1 list of the “100 Greatest Artists of All Time”.
Members:
-Angus Young – lead guitar (1973–present)
- Cliff Williams – bass guitar, backing vocals (1977–2016[retired following the Rock or Bust Tour])
- Stevie Young – rhythm guitar, backing vocals (1988 [touring member], 2014–present)
- Chris Slade – drums (1989–1994, 2015–present)
- Brian Johnson – lead and backing vocals (1980–2016 [Indefinite Hiatus])
- Axl Rose – lead vocals (2016 [touring member])
Former members
- Malcolm Young – rhythm guitar, backing vocals (1973–2014)
- Dave Evans – lead vocals (1973–1974)
- Bon Scott – lead vocals (1974–1980)
- Mark Evans – bass guitar (1975–1977)
- Phil Rudd – drums (1975–1983, 1994–2015)
- Simon Wright – drums (1983–1989)', 21);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (22, 'My Chemical Romance', 'My Chemical Romance was an alt/punk/hardcore rock band that produced four studio albums and a compilation album over their twelve year lifespan from 2001-2013. They have touched the hearts of millions through their honest, raw lyrics and inspirational stories.
The band started after front-man and founder Gerard Way witnessed the 9/11 terror attacks in New York City. He felt compelled to empower people and make a difference in the world. As a result, he wrote the band’s first song, “Skylines And Turnstiles.” He shared the lyrics with his friend Matt Pelissier, who agreed to be the then-unnamed band’s drummer. Gerard then recruited Ray Toro, whom he used to be in a band with as the lead guitarist, and eventually invited his brother Mikey Way to be the bassist, and Frank Iero to be the rhythm guitarist.
Their first album, I Brought You My Bullets, You Brought Me Your Love, was released in 2002 and was recorded in Matt Pelissier’s attic. Because of this, some of the songs are lovingly referred to as the “attic demos.” The album’s copyright warning reads:
Unauthorized duplication is a violation of applicable laws and will result in Gerard coming to your house and sucking your blood.
The band shot to stardom with their second album, Three Cheers For Sweet Revenge, which was released with Eyeball Records. Songs like “I’m Not Okay,” “Helena,” and “The Ghost Of You” captivated listeners and expanded their fan-base. Following its release, the band played on the 2005 Vans Warped Tour, along with bands like Fall Out Boy and Avenged Sevenfold. Drummer Matt Pelissier decided to leave the band and was replaced by Bob Bryar.
The Black Parade, arguably the band’s most popular effort, was released in 2006, and was a concept album detailing the death of a character called The Patient. It was their first album with Warner Brothers records, and the last with Bob Bryar as drummer. Years after the album dropped, Gerard Way revealed that the band planned on calling it a day and splitting up:
When the tour basically ended with us conquering the world, we were supposed to ride off into the sunset. I can’t think of a better ending than that. [It didn’t end there] because you get into careers, mortgages, families, crews, people, the machine itself – not to mention expectations of a record label that invested quite a bit in you, that would like more out of you, a fanbase that wants more out of you.
Luckily for fans, TBP wasn’t the last of My Chem – they followed up the smash hit in 2010 with their final studio album, Danger Days. The album acted as a rebirth from the sad concepts of their previous releases, and involved more upbeat tracks and messages.
After Danger Days, Conventional Weapons, a compilation album featuring ten previously unreleased songs recorded in 2009 was gradually released. These tracks feature Bob Bryar prior to his departure from the band. The album was never released due to unsatisfaction from the band’s previous producer.
However, the fun times and smiles didn’t last very long. On March 22nd, 2013, the band announced that they were breaking up. A compilation album titled May Death Never Stop You was released, featuring a new song, Fake Your Death. Despite the upset fans'' pleas, no definite answer has been given as to why they split. Some claim they had trouble with their record label, while others believe Gerard had relapsed into alcohol dependence. Whether the world will ever know what truly happened is a mystery, but one thing is for sure: My Chemical Romance has made a difference in the world, just as they aspired to do from day one.
On October 31, 2019, the band reunited with a tweet listing a tour.', 22);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (23, 'The Killers', 'Founded by Brandon Flowers and Dave Keuning in 2001 in Las Vegas, The Killers have become arguably the most successful rock band from Nevada. After their hit 2004 debut album Hot Fuss, with singles such as “Somebody Told Me” and “Mr. Brightside,” the band has released four other studio albums, along with a rarities collection, Christmas EP, a live album, and a Greatest Hits album. The band released their fifth studio album, Wonderful Wonderful, in September 2017.', 23);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (24, 'Slowdive', 'Slowdive are an English shoegaze/dream pop band that formed in Reading, Berkshire in 1989. The band consists of Rachel Goswell on vocals and guitar, Simon Scott on drums, Neil Halstead on vocals and guitar, Nick Chaplin on bass and Christian Savill on guitar. Several other drummers also briefly played with the band, including Adrian Sell, Neil Carter and Ian McCutcheon. Halstead is the band’s primary songwriter.
Soon after the release of Pygmalion, some of the members left the band and the remaining members renamed the band Mojave 3. Slowdive reunited in 2014, soon releasing a self-titled album.', 24);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (25, 'The Cranberries', 'The Cranberries are an Irish band who found major international success throughout the 1990s as a part of the alternative rock movement. The group’s lineup includes Dolores O''Riordan (singer and songwriter), Noel Hogan (guitarist and songwriter), Mike Hogan (bassist) and Fergal Lawler (drummer). Originally formed in 1989 under the name The Cranberry Saw Us, the band released an independent EP in 1991 that caught the attention of the industry. SPIN Magazine described the band’s sound as “dreamy swirl pop, midway between The Smiths and the Cocteau Twins cradling the will-o’-the-wispy vocals of Dolores O’Riordan.”
In 1992, the band began recording their first album for Island Records with Stephen Street, a producer best known for working with The Smiths. Their debut, Everybody Else is Doing It So Why Can’t We?, was initially ignored when released in early 1993, and it wasn’t until that fall—after the band opened for Suede and Duran Duran on their US tours—that MTV picked up on their single “Linger”. The song eventually peaked at #4 on the US Pop chart in 1994, and the album sold five million copies. Success around the world followed.
Later that year, the band released their sophomore album No Need To Argue, which went on to sell 7 million copies in the US. The lead single, “Zombie,” was a departure from the wistful love songs the band was known for, showcasing aggressive distorted guitars and a bold political message. The song was an immediate smash, hitting at #1 in several countries and topping the US Modern Rock chart. The follow-up single “Ode To My Family,” was a top 40 hit as well.
In 1996, The Cranberries collaborated with Bruce Fairbairn (Bon Jovi, Aerosmith) on their third album To The Faithful Departed, which experimented with new sounds and continued the band’s embrace of hard rock. The album received mixed reviews and sold about half as well as their previous albums, but it did include the #1 US Modern Rock song “Salvation”.
The band’s 1999 album Bury The Hatchet—self-produced by The Cranberries and engineer Ben Fenner—went gold and failed to produce any top 40 hits in the US. In 2002, they reunited with producer Stephen Street on Wake Up And Smell The Coffee, but the mainstream had largely lost interest in the band by this point. A hiatus—during which O’Riordan released two solo albums—followed. The band reunited in 2012 for the independent album Roses.
On Jan. 16, 2018, an official spokesperson for the Cranberries announced that Dolores O''Riordan died “suddenly” in her home in London. She was 46.', 25);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (26, 'Imagine Dragons', 'Led by frontman Dan Reynolds, Imagine Dragons is an American alt-rock band that originated in Las Vegas. While the band began in 2008, the group boasted an entirely different roster than most are familiar. Before releasing their debut album, Night Visions in 2012, the band released eight EPs over four years, constantly shifting their sound and roster from folk to the crowd-shattering anthems they’ve been known for since.
The band’s roster was finalized before Night Visions‘ release with Daniel Platzman on the drums, Wayne Sermon on guitar, and Ben McKee on bass. Their break-out single, “Radioactive” was essential to putting Vegas on the map musically, citing The Killers before them. The song went on to becoming an international success, shattering the record for the most weeks on the Billboard Hot 100 at 87 straight weeks.
It wasn’t until 2015 the band released their sophomore album, Smoke + Mirrors. The album was extremely deviant from their freshman album, characterized by an accentuation of their Rock roots and an internal struggle, later described by Reynolds as his bout with severe depression. After a self-imposed hiatus in 2016, the band premiered their third album, Evolve, during Super Bowl LI. As the title suggests, Evolve was seen as another evolution of the band’s sound, with a newfound focus around Pop and EDM. It only took a year for the band to release their fourth full-length album, Origins, characterized as a sister album to Evolve.', 26);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (27, 'Bruce Springsteen', 'Bruce Springsteen is a rock ‘n’ roll icon from the great state of New Jersey. Nicknamed “The Boss,” he’s known for spirited sax-powered anthems about working-class people making their way in the world. Backed by the trusty E Street Band, he’s sold more than 120 million records, won numerous awards (including 20 Grammys and an Oscar), sold out stadiums around the globe, and earned a place alongside his teenage heroes in the Rock and Roll Hall of Fame.
Although he’s a living legend who ranks among the most important artists in rock history, Springsteen wasn’t an overnight success. Around the time of his first album, 1973’s Greetings from Asbury Park, N.J., he was dismissed as just another “new Dylan"—some scruffy folk singer with a decent vocabulary looking to follow in Bob’s footsteps. In the decade that followed, Springsteen proved himself to be much more.
His breakthrough came with his third album, 1975’s Born to Run. The record hit No. 3 on the Billboard 200 and landed the singer-songwriter on the cover of both Time and Newsweek. Bruce nabbed his first chart-topping album five years later with The River, and in 1984, he went global with Born in the U.S.A., a critical and commercial smash that produced seven Top 10 singles.
With its mix of upbeat rock ‘n’ roll and hard-hitting lyrics about unemployment, racism, and the collapse of the American dream, Born in the U.S.A. captures much of what makes Springsteen such a unique artist. More than 30 years later, he remains a spokesman for baby boomers and a hero to young rock fans looking for an example of a guy who’s never sold out or phoned it in. He speaks truth to power—then jumps up on the piano and cues the sax solo.
To this day, the Boss gives three-hour concerts that typically end with him inviting fans onstage to groove along to “Dancing In the Dark,” one of his ‘80s favorites. Many have called on him to run for president, but don’t expect him to quit his day job.', 27);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (28, 'Miley Cyrus', 'Miley (Ray) Cyrus is an American singer, songwriter and actress, as well as the daughter of country singer Billy Ray Cyrus. She was named Destiny Hope Cyrus at birth but was given the nickname “Smiley” because she was always grinning. The name stuck and she legally changed it in 2008.
Her singing career started simultaneously with her role in the Disney Channel television series Hannah Montana, which made her a teen idol. She was featured on the 2006 soundtrack of Hannah Montana. After signing a recording contract with Hollywood Records in 2007, she released Hannah Montana 2: Meet Miley Cyrus. The album served as both the series'' soundtrack and Cyrus'' debut studio album.
With the 2010 release of Can’t Be Tamed, Cyrus developed a more mature image with a dance-oriented sound. The album caused controversy due to the lyrics and music video of Can’t Be Tamed.
In 2013, Cyrus signed to RCA Records and released [Bangerz], which debuted her new hip-hop influenced sound. She became one of the most award-nominated pop stars in the world. [Bangerz] brought Miley her biggest success, earning her more than 40 awards and a lot of views on YouTube. She won  her first Video Music Award, in the category ‘''Best Video of The Year’‘ with the smash hit ’‘Wrecking Ball."
In 2015, Miley Cyrus released [Miley Cyrus & Her Dead Petz'' for free, available on SoundCloud, at the Video Music Awards. It was the first digital album to reach 100 million streams.
In an interview with Billboard, in May 2017, Cyrus talked about leaving the hip-hop scene because it was too much “Lamborghini, got my Rolex, got a girl on my cock.“ Her father shared with Billboard: "This is Miley leaning into her roots more than I’ve ever heard.”
A week later, Cyrus went back to her country roots with the release of “Malibu”.', 28);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (29, 'The Defaults', '', 29);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (30, 'She Wants Revenge', 'She Wants Revenge is an American musical duo, based in San Fernando Valley, California. The group’s debut album She Wants Revenge was released in early 2006, with three singles to follow (“These Things,” a video featuring Shirley Manson from Garbage, “Out of Control,” and “Tear You Apart” for which the video was directed by Joaquin Phoenix).', 30);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (31, 'David Bowie', 'David Bowie (1947 – 2016) was a British musician, and one of the most iconic rock stars with a widely diverse career where he frequently changed his appearance and musical style, resulting in an acclaimed  discography comparable to other stalwarts such as The Beatles and Bob Dylan. Born David Robert Jones, Bowie quickly renamed himself to prevent confusion with The Monkees singer Davy Jones. Enduring many early missteps, he rose to prominence when his most famous song, “Space Oddity,” was played during the coverage of the Apollo 11 moon landing.
Despite this early breakthrough, Bowie remained a cult figure for several years. Even the release of Hunky Dory, his first great album, went largely unnoticed. Bowie only lodged himself firmly in the public consciousness when he announced his bisexuality and created Ziggy Stardust in early 1972. A Martian who combined the debauchery of Iggy Pop with the artistry of Lou Reed, Ziggy was the main character in Bowie’s breakthrough album, and his public persona for eighteen months.
Bowie used his new-found popularity to move to America, and dabble with new musical directions and cocaine. Diamond Dogs and Young Americans continue to divide critics, but Station To Station found Bowie at a new creative peak, despite escalating drug use and related health issues.
Moving back to Europe helped Bowie reach even greater musical heights. He recorded his iconic “Berlin Trilogy” – Low, “Heroes”, and Lodger, with Brian Eno and Tony Visconti (despite the name, only Heroes was recorded in Berlin), and produced Iggy Pop’s first two solo albums. This was followed by the hard-rocking Scary Monsters (And Super Creeps), and disco-influenced Let’s Dance.
Bowie entered a period of critical apathy during the 1980s, as albums like Tonight and Never Let Me Down fell relatively flat. These were his Tin Machine days, and they paved the way for a renaissance of huge proportions, with albums such as 1. Outside, Earthling, Heathen, and Reality reclaiming his status as a number one pop star. Radio silence then ensued for much of the 2000s, until he surprisingly issued 2013’s The Next Day, recorded in secret and released to critical acclaim.
David Bowie passed away on January 10, 2016, two days after his 69th birthday and the release of his last album, Blackstar.', 31);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (32, 'Warbly Jets', '', 32);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (33, 'Jon Bellion', 'Jon Bellion is an American singer, songwriter, producer and rapper born and raised in Long Island, New York. He was born on December 26, 1990 and is signed with both Capitol Records and Visionary Music Group, alongside Logic. He first started making beats on his brother’s beat pad when he was a young kid. He would end up going to college on a basketball scholarship only to drop out to pursue his music career.
Jon pulls influences from many artists and producers, including Kanye West, Timbaland and J. Dilla. His ability to blend genres often makes it tough to categorize his sound, but his inspirations are evident throughout his projects.
Fun fact: Jon doesn’t actually know how to read music, as he has mentioned in interviews and on Twitter.
Jon’s name started getting more recognition after writing the hook for Eminem’s “The Monster”. In 2015, he was featured on Zedd’s song “Beautiful Now” and has also received credits with the likes of CeeLo Green on the track “Robin Williams” and for writing & producing “Trumpets” by Jason Derulo.
Prior to releasing his debut studio album, Jon released 4 mix-tapes: Scattered Thoughts Vol.1, Translation Through Speakers, The Separation, and The Definition. He has also made other songs and covered songs that aren’t on the mix-tapes that can be found on SoundCloud or YouTube. These songs are filled with collaborations between him and Beautiful Mind.
In 2016, he released his first studio album, The Human Condition, debuting at #1 on iTunes. It’s lead single, All Time Low, peaked at #16 on the Hot 100, reached worldwide success and has amassed over 300 million streams on Spotify.
Since its release, Bellion has headlined an international tour, performed alongside twenty one pilots, and 3 sold-out national tours for the album. Since those 3 tours, Jon said on the third tour “I don’t give a shit if we can come back and sell out a football stadium, I’m going the fuck home and making some new music”.
After months of cryptic Instagram, Twitter and Facebook posts, on the 10th of October, Jon announced his next album, Glory Sound Prep, which came out November 9th 2018.', 33);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (34, 'Hozier', 'Andrew Hozier-Byrne (March 17, 1990 – ), known professionally as Hozier, is an Irish singer and songwriter known best for his critically acclaimed hit song, “Take Me To Church”.
The son of a blues musician, Hozier’s unique sound is a blend of blues, gospel, and soul.  From 2009 to 2012, he toured the world with Anuna, an Irish choral group.
His first EP, Take Me To Church, was released in 2013, followed by From Eden in 2014.  His full-length debut album Hozier, was released later that year on September 19th.  The song, “Take Me to Church” peaked at number 100 on the U.S. Billboard charts and was followed by a successful international tour.
His second album Wasteland, Baby! released in 2019.', 34);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (35, 'John Denver', 'John Denver was born 1943 in USA and died 1997 from an aircrash at just 53 years old. During his lifetime he became internationally known for his songs about nature and simple life, and released 25+ albums.
Born Henry John Deutschendorf, Jr., at age 11 he started playing the guitar and a few years later he was perfoming at local clubs. He adopted the name Denver after the state captial of his favourite US state, Colorado. In 1965 he joined The Mitchell Trio, and in 1966 he self-released his first solo album.
Between 1969 and 1975 Denver rose to fame with some of his highest charting albums and songs, including his signature song Take Me Home, Country Roads. It was in the 70s that he began with his activism and humanitarian work, which he continued all into his later years, focusing on environment and peace.
Denver never stopped making music, and at the end of his life and career he had recieved an Emmy, two Grammies, and several other rewards and recognitions. His legacy in folk, country, and even music history itself, lives on.', 35);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (36, 'Mark Ronson', 'Mark Daniel Ronson (born 4 September 1975 in London) is an English musician, DJ, singer, songwriter and record producer.', 36);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (37, 'Bruno Mars', 'Peter Gene Hernandez (born October 8, 1985), known by his stage name Bruno Mars, is an American singer-songwriter and record producer.
Raised in Honolulu, Hawaii, by a family of musicians, Mars began making music at a young age and performed in various musical venues in his hometown throughout his childhood. He graduated from high school and moved to Los Angeles, California, to pursue a musical career.
His debut album Doo-Wops and Hooligans was released in 2010 with three hit singles. His second album, Unorthodox Jukebox, was released in 2012 and quickly reached the number one selling album in the U.S. at the time while spawning multiple hit singles of its own. On Friday, October 7th, 2016, he released the lead single and music video for “24k Magic,” from his third studio album of the same name.
Having sold over 100 million records in the short span of his career, he is one of the best-selling artists of all time. To date, he has had six number-one singles on the Billboard 100 and having launched his career in 2010 he is the fastest artist to get 5 number one hits since rockstar, Elvis Presley.
Mars has produced many hit songs for other artists with his production team, The Smeezingtons, that came together in 2009.', 37);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (38, 'The Verve', 'The Verve were one of the most popular bands of the Britpop era thanks to their massive third album, Urban Hymns, which is one of the best-selling albums in British chart history. However, the band from Wigan, which was formed by Richard Ashcroft, Nick McCabe, Simon Jones and Peter Salisbury in 1990, also achieved success with their other albums, particularly their second, A Northern Soul.
The band split up in 1999 amid rising tensions among the band members, of which one was now keyboardist Simon Tong. The controversy regarding the credits of their huge hit “Bitter Sweet Symphony” also contributed towards these tensions. The band reunited in 2007, despite Ashcroft’s earlier dismissal of the idea of a reunion:
You’re more likely to get all four Beatles on stage.
They then released their fourth album, Forth in 2008, but disbanded again shortly afterwards. Since their break-up, the individual members, Ashcroft in particular, have pursued successful solo careers.', 38);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (39, 'Bebe Rexha', 'Born on August 30, 1989, Bleta Rexha–widely known by her stage name Bebe Rexha, with Bebe meaning “bumblebee”–is an American singer and songwriter hailing from Brooklyn, New York. Her Albanian background and passion for music at the young age of 4 led her to pursue her love for music through Tottenville High School on Staten Island.
She is best known for being featured on the hit singles “Take Me Home” by Cash Cash, “Hey Mama” by David Guetta and “Me, Myself and I” by G-Eazy. She is also known for being the lead vocalist of the American band Black Cards, which was created by Pete Wentz, lead bassist of Fall Out Boy.
She has worked producing and writing for several different artists and most notably co-wrote the number-one US Billboard Hot 100 hit “The Monster” by Eminem featuring Rihanna.
She published two EPs in 2017: All Your Fault Pt. 1 & Pt. 2. “Meant To Be”, which is in part 2, has entered US Billboard Hot 100 and is the longest No.1 on the Billboard Hot Country songs.
“Meant To Be” would also be later included in Bebe’s debut album Expectations, the latter being released on June 22, 2018. The album peaked at #13 on the Billboard Hot 200.', 39);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (40, 'Martin Garrix', 'Martijn Gerard Garritsen, better known by his stage name Martin Garrix, is a Dutch DJ/producer who runs his own label STMPD RCRDS.
His earliest success came with the track “Animals,” which was a Top 10 in multiple countries. Garrix came to the world spotlight when his track Error 404 was played by Fatboy Slim during his set at Ultra Music Festival 2013. Within 2 years Martin went from being in the crowd listening to his song being played, to spinning on the main stage of arguably the biggest festival in Eletronic Music.
He has since been dubbed by many as the savior of EDM music, and is the youngest person to not only perform at the Ultra Music Festival but to also headline it. Inspired by watching Tiësto spin at the 2004 Athens Olympics, Garrix decided to fully pursue music at a young age while simultaneously graduating with full honors from school.
Although young, Martin has worked with some of the biggest acts in music including Avicii, Bebe Rexha, Tiësto, Usher, and many more.  Prepare for very big things to come from this talented individual.', 40);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (41, 'A.R.Rahman', '', 41);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (42, 'Darshan Raval', '', 42);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (43, 'Arijit Singh', 'Arijit Singh is a Bengali singer, music producer, recording artist and music programmer. He sings predominantly in Hindi and Bengali, but has also performed in various other Indian languages. Singh is regarded as one of the most versatile and successful singers in the history of South Asian music and the Bollywood cinema.', 43);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (44, 'Amit Trivedi', 'Amit Trivedi is an Indian film composer, musician, singer and lyricist. After working as a theatre and jingle composer and composing for non-film albums, he debuted as a film composer in the 2008', 44);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (45, 'Ritviz', '21-year old Singer, DJ & Dance Music Producer. His music is bass heavy, and rich in eastern sounds owing to his training as a Hindustani classical musician since the age of 6. He was recently announced as the winner of Bacardi House Party Sessions India, where his latest single “Udd Gaye” was handpicked & released, along with a music video, by AIB & Nucleya. An instant hit, the music video has garnered 2.5 Million views in just four weeks of it’s release, and the track has close to 2 Million plays on Saavn & iTunes.', 45);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (46, 'Arjun Kanumgo', '', 46);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (47, 'The Local Train', '', 47);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (48, 'Yo Yo Honey Singh', 'Hirdesh Singh, better known by his stage name Yo Yo Honey Singh or Honey Singh is an Indian rapper, music producer, singer and film actor. He started as a session and recording artist, and became a Bhangra producer. He’s an Indian rapper who raps in Hindi and Punjabi.

Born: March 15, 1983 (age 32), Hoshiarpur, India
Full name: Hirdesh Singh
Spouse: Shalini Singh (m. 2011)', 48);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (49, 'Milind gaba', '', 49);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (50, 'Guru Randhawa', 'Guru Randhawa (गुरु रंधावा) is an Indian, Punjabi singer-songwriter and music composer from Punjab, India. Guru Randhawa is associated with Indi-pop and Punjabi Bhangra. His famous tracks include High Rated Gabru, Suit, Yaar Mod Do, Patola and Fashion, etc. He has performed in the IPL opening ceremony too, and at various other platforms of National and International repute. He made his Bollywood singing debut with Hindi Medium.', 50);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (51, 'Mika Singh', 'Mika Singh is an Indian singer who has sung many popular songs for film soundtracks in various languages.', 51);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (52, 'Luis Fonsi', '', 52);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (53, 'Daddy Yankee', 'Ramón Luis Ayala Rodríguez (nacido el 3 de febrero de 1977), mejor conocido como Daddy Yankee, es un cantante, rapero, compositor, actor y productor puertorriqueño.
Su álbum Barrio Fino lanzado en 2004, se convirtió en el primer disco de reggaetón en conseguir el puesto número 1 en la lista de los mejores álbumes de Estados Unidos. Su primer sencillo llamado “Gasolina”, se conoce como la canción que hizo que tanto él como el género urbano reggaetón se hicieran famosos en el mercado en el año 2005. Barrio Fino se puso a la cabeza en la lista de los éxitos de Estados Unidos durante 24 semanas y se convirtió en el álbum latino más vendido de la década entre 2000-2009 en los Estados Unidos.
En 2017, Daddy Yankee hizo historia en la industria musical con la canción “Despacito”. La colaboración con el cantante puertorriqueño Luis Fonsi ha alcanzado más de 5 billones de visitas en YouTube y se ha convertido en un éxito mundial alcanzando la posición número uno en 45 países. “Despacito (Remix)”, que fue lanzado 4 meses después, cuenta con la colaboración del cantante canadiense Justin Bieber, que dicha colaboración ayudó que la canción llegara a varios países que no hablan español. La canción se convirtió en la tercera canción en español número 1 en los Estados Unidos, y la primera número 1 en idioma español desde la “Macarena (Bayside Boys Remix)” en 1996, y ha recibido varias certificaciones en todo el mundo.

Ramón Luis Ayala Rodríguez (born February 3, 1977), known by his stage name Daddy Yankee, is a Puerto Rican singer, rapper, songwriter, actor and record producer.
His 2004 album Barrio Fino became the first reggaeton record to achieve a number 1 debut on the US Top Latin Albums chart. Its lead single “Gasolina” is cited as the song that introduced both him and reggaeton music into the mainstream market during 2005. Barrio Fino topped the US Latin chart for 24 weeks and became the top selling Latin album of the decade between 2000-2009 in the United States.
In 2017 Daddy Yankee made history in the music industry with the song Despacito. The collaboration with Puerto Rican singer Luis Fonsi has reached more than 5 billion views on YouTube and became a worldwide chart success, reaching number 1 in 45 countries. Despacito (Remix), released four months later, features Canadian singer Justin Bieber, and helped the single’s chart performance in various non-Spanish-language countries. The song became the third Spanish-language number 1 in the United States, and the first Spanish-language number 1 since the Macarena (Bayside Boys Remix) in 1996, and recevied various certifications around the world.', 53);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (54, '', '', 54);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (55, ' J Balvin', 'José Álvaro Osorio Balvín, conocido como J Balvin, es un cantante colombiano de reguetón y pop latino, que ha logrado posicionarse tanto en el mercado musical hispanoparlante como el anglosajón, llegando a colocar sus temas en número uno, en varias listas musicales, entre ellas Billboard.​
Desde muy joven mostró interés por la música.​ En sus inicios musicales, mostró pasión por el rock y su actual admiración por bandas como Nirvana. Luego formó un grupo de rap y en 2004 lanza su primer canción como solista. En 2010 se convierte en artista revelación por varias emisoras de Colombia. Ese mismo año firmó un contrato musical con EMI Music, así lanza su álbum debut Real, que fue certificado disco de oro en Colombia. En el 2012, lanza su segundo álbum *El Negocio, este tuvo tres sencillos, “Sin Compromiso”, “Me Gustas Tú” y “En Lo Oscuro”. “En Lo Oscuro” se ubicó en la primera posición del listado National Report de Colombia, siendo su primer número uno en su país.
 La explosión de Balvin se debió en gran medida a que “6 AM” con Farruko y poco después “Ay Vamos” marcaron historia en el reggaeton, siendo uno de los videos latinos más vistos de todos los tiempos con más de 600 millones de visitas. El éxito de “6 AM” y “ Ay Vamos” hizo Balvin el primer artista en recibir una certificación de diamantes en el campo latinoamericano del RIAA, que denota las ventas digitales de 600.000 unidades .
En enero de 2015, J Balvin estrenó “Ginza” en el Premios Juventud, que, en ese momento, rompió el récord de más puntos de vista para un video de música latina en las primeras 24 horas, a más de 2 millones de visitas.', 55);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (56, 'Willy William', 'Willy William (born April 14, 1980) is a French-Mauritian DJ, music producer and singer songwriter and artist famous for his club remixes and vocal collaborations with a number of dance music artists.', 56);
INSERT INTO Artist(artistId, artistName, briefBio, ranking) VALUES (57, 'Shakira', 'Shakira Isabel Mebarak Ripoll, conocida más comúnmente como Shakira, es una cantante, compositora, bailarina, productora discográfica, coreógrafa y modelo colombiana. Nacida y criada en Barranquilla, comenzó a actuar en la escuela, demostrando influencias y habilidades de danza del vientre en latín, árabe y rock and roll. Shakira lanzó sus primeros álbumes de estudio Magia y Peligro a principios de la década de 1990, sin lograr el éxito comercial. Sin embargo, ella saltó a la fama en América Latina con su debut en el sello principal Pies Descalzos (1996) y su cuarto álbum ¿Dónde Están Los Ladrones? (1998) .
Su álbum homónimo Shakira marcó su décimo lanzamiento en el estudio.

English:
Shakira Isabel Mebarak Ripoll, known more commonly as Shakira, is a Colombian singer-songwriter, dancer, record producer, choreographer, and model. Born and raised in Barranquilla, she began performing in school, demonstrating Latin, Arabic, and rock and roll influences and belly dancing abilities. Shakira released her first studio albums Magia and Peligro in the early 1990s, failing to attain commercial success. However, she rose to prominence in Latin America with her major-label debut Pies Descalzos (1996) and her fourth album ¿Dónde Están Los Ladrones? (1998).
Her eponymous album Shakira marked her tenth studio release.', 57);
