INSERT INTO Genre(songId, sgenre) VALUES (1, 'Hip-Hop');
INSERT INTO Genre(songId, sgenre) VALUES (1, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (2, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (3, 'Dance');
INSERT INTO Genre(songId, sgenre) VALUES (3, 'Electronic');
INSERT INTO Genre(songId, sgenre) VALUES (4, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (5, 'Electropop');
INSERT INTO Genre(songId, sgenre) VALUES (5, 'Dancehall');
INSERT INTO Genre(songId, sgenre) VALUES (6, 'Electropop');
INSERT INTO Genre(songId, sgenre) VALUES (6, 'Dance-pop');
INSERT INTO Genre(songId, sgenre) VALUES (7, 'Synth-pop');
INSERT INTO Genre(songId, sgenre) VALUES (7, 'Dance-pop');
INSERT INTO Genre(songId, sgenre) VALUES (8, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (8, 'Future-bass');
INSERT INTO Genre(songId, sgenre) VALUES (9, 'Dance-pop');
INSERT INTO Genre(songId, sgenre) VALUES (10, 'Synth-pop');
INSERT INTO Genre(songId, sgenre) VALUES (11, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (12, 'Folk');
INSERT INTO Genre(songId, sgenre) VALUES (13, 'Trap');
INSERT INTO Genre(songId, sgenre) VALUES (13, 'Hip-Hop');
INSERT INTO Genre(songId, sgenre) VALUES (13, 'Pop-electro');
INSERT INTO Genre(songId, sgenre) VALUES (14, 'Pop Rock');
INSERT INTO Genre(songId, sgenre) VALUES (14, 'Blues Rock');
INSERT INTO Genre(songId, sgenre) VALUES (14, 'Blue eyed Rock');
INSERT INTO Genre(songId, sgenre) VALUES (14, 'Soft Rock');
INSERT INTO Genre(songId, sgenre) VALUES (15, 'Rock');
INSERT INTO Genre(songId, sgenre) VALUES (16, 'Folk Rock');
INSERT INTO Genre(songId, sgenre) VALUES (17, 'Blues');
INSERT INTO Genre(songId, sgenre) VALUES (18, 'Rock');
INSERT INTO Genre(songId, sgenre) VALUES (19, 'Pop Rock');
INSERT INTO Genre(songId, sgenre) VALUES (20, 'Hard Rock');
INSERT INTO Genre(songId, sgenre) VALUES (20, 'Heavy Metal');
INSERT INTO Genre(songId, sgenre) VALUES (20, 'Arena Rock');
INSERT INTO Genre(songId, sgenre) VALUES (21, 'Hard Rock');
INSERT INTO Genre(songId, sgenre) VALUES (21, 'Heavy Metal');
INSERT INTO Genre(songId, sgenre) VALUES (21, 'Arena Rock');
INSERT INTO Genre(songId, sgenre) VALUES (22, 'Hard Rock');
INSERT INTO Genre(songId, sgenre) VALUES (22, 'Heavy Metal');
INSERT INTO Genre(songId, sgenre) VALUES (22, 'Arena Rock');
INSERT INTO Genre(songId, sgenre) VALUES (23, 'Pop Punk');
INSERT INTO Genre(songId, sgenre) VALUES (23, 'Alternative Rock');
INSERT INTO Genre(songId, sgenre) VALUES (23, 'Emo');
INSERT INTO Genre(songId, sgenre) VALUES (24, 'Hearland Rock');
INSERT INTO Genre(songId, sgenre) VALUES (24, 'New Wave');
INSERT INTO Genre(songId, sgenre) VALUES (25, 'Pop Rock');
INSERT INTO Genre(songId, sgenre) VALUES (26, 'Baroque Rock');
INSERT INTO Genre(songId, sgenre) VALUES (26, 'Chamber Rock');
INSERT INTO Genre(songId, sgenre) VALUES (27, 'EDM');
INSERT INTO Genre(songId, sgenre) VALUES (27, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (27, 'Synth-pop');
INSERT INTO Genre(songId, sgenre) VALUES (28, 'Ambient');
INSERT INTO Genre(songId, sgenre) VALUES (28, 'Indie Rock');
INSERT INTO Genre(songId, sgenre) VALUES (29, 'Alternative Rock');
INSERT INTO Genre(songId, sgenre) VALUES (29, 'Soft Rock');
INSERT INTO Genre(songId, sgenre) VALUES (30, 'Electro-pop');
INSERT INTO Genre(songId, sgenre) VALUES (30, 'Dance-pop');
INSERT INTO Genre(songId, sgenre) VALUES (31, 'Pop Rock');
INSERT INTO Genre(songId, sgenre) VALUES (31, 'Indie Rock');
INSERT INTO Genre(songId, sgenre) VALUES (31, 'Alternative Rock');
INSERT INTO Genre(songId, sgenre) VALUES (32, 'Pop Rock');
INSERT INTO Genre(songId, sgenre) VALUES (32, 'Indie Rock');
INSERT INTO Genre(songId, sgenre) VALUES (32, 'slowtempo');
INSERT INTO Genre(songId, sgenre) VALUES (33, 'R&B');
INSERT INTO Genre(songId, sgenre) VALUES (34, 'Hard Rock');
INSERT INTO Genre(songId, sgenre) VALUES (34, 'Post Grunge');
INSERT INTO Genre(songId, sgenre) VALUES (35, 'Future Bass');
INSERT INTO Genre(songId, sgenre) VALUES (36, 'New Wave');
INSERT INTO Genre(songId, sgenre) VALUES (37, 'Glam Rock');
INSERT INTO Genre(songId, sgenre) VALUES (37, 'Proto Punk');
INSERT INTO Genre(songId, sgenre) VALUES (38, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (38, 'House');
INSERT INTO Genre(songId, sgenre) VALUES (39, 'Rock');
INSERT INTO Genre(songId, sgenre) VALUES (40, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (40, 'Rock');
INSERT INTO Genre(songId, sgenre) VALUES (41, 'Blues');
INSERT INTO Genre(songId, sgenre) VALUES (41, 'soul');
INSERT INTO Genre(songId, sgenre) VALUES (41, 'R&B');
INSERT INTO Genre(songId, sgenre) VALUES (41, 'Indie Rock');
INSERT INTO Genre(songId, sgenre) VALUES (42, 'Country');
INSERT INTO Genre(songId, sgenre) VALUES (43, 'Country-disco');
INSERT INTO Genre(songId, sgenre) VALUES (43, 'pop');
INSERT INTO Genre(songId, sgenre) VALUES (44, 'Funk Pop');
INSERT INTO Genre(songId, sgenre) VALUES (44, 'Soul');
INSERT INTO Genre(songId, sgenre) VALUES (44, 'Boogie');
INSERT INTO Genre(songId, sgenre) VALUES (44, 'Disco Pop');
INSERT INTO Genre(songId, sgenre) VALUES (45, 'Britpop,Alternative Rock');
INSERT INTO Genre(songId, sgenre) VALUES (46, 'Britpop');
INSERT INTO Genre(songId, sgenre) VALUES (47, 'Pop Rock');
INSERT INTO Genre(songId, sgenre) VALUES (47, 'Blues Rock');
INSERT INTO Genre(songId, sgenre) VALUES (47, 'Blue eyed Rock');
INSERT INTO Genre(songId, sgenre) VALUES (47, 'Soft Rock');
INSERT INTO Genre(songId, sgenre) VALUES (48, 'Dance');
INSERT INTO Genre(songId, sgenre) VALUES (48, 'Electronic');
INSERT INTO Genre(songId, sgenre) VALUES (49, 'Pop Rock');
INSERT INTO Genre(songId, sgenre) VALUES (49, 'Blues Rock');
INSERT INTO Genre(songId, sgenre) VALUES (49, 'Blue eyed Rock');
INSERT INTO Genre(songId, sgenre) VALUES (49, 'Soft Rock');
INSERT INTO Genre(songId, sgenre) VALUES (50, 'Pop Rock');
INSERT INTO Genre(songId, sgenre) VALUES (50, 'Blues Rock');
INSERT INTO Genre(songId, sgenre) VALUES (50, 'Blue eyed Rock');
INSERT INTO Genre(songId, sgenre) VALUES (50, 'Soft Rock');
INSERT INTO Genre(songId, sgenre) VALUES (51, 'Indie Rock');
INSERT INTO Genre(songId, sgenre) VALUES (51, 'Folk Rock');
INSERT INTO Genre(songId, sgenre) VALUES (51, 'Jangle Pop');
INSERT INTO Genre(songId, sgenre) VALUES (51, 'Post Rock');
INSERT INTO Genre(songId, sgenre) VALUES (52, 'Electropop');
INSERT INTO Genre(songId, sgenre) VALUES (53, 'Pop Rock');
INSERT INTO Genre(songId, sgenre) VALUES (53, 'Indie Rock');
INSERT INTO Genre(songId, sgenre) VALUES (53, 'Alternative Rock');
INSERT INTO Genre(songId, sgenre) VALUES (54, 'Pop Rock');
INSERT INTO Genre(songId, sgenre) VALUES (54, 'Indie Rock');
INSERT INTO Genre(songId, sgenre) VALUES (54, 'Alternative Rock');
INSERT INTO Genre(songId, sgenre) VALUES (55, 'Future Bass');
INSERT INTO Genre(songId, sgenre) VALUES (56, 'Britpop');
INSERT INTO Genre(songId, sgenre) VALUES (57, 'Folk Rock');
INSERT INTO Genre(songId, sgenre) VALUES (58, 'Rock');
INSERT INTO Genre(songId, sgenre) VALUES (59, 'Pop Rock');
INSERT INTO Genre(songId, sgenre) VALUES (59, 'Blues Rock');
INSERT INTO Genre(songId, sgenre) VALUES (59, 'Blue eyed Rock');
INSERT INTO Genre(songId, sgenre) VALUES (59, 'Soft Rock');
INSERT INTO Genre(songId, sgenre) VALUES (60, 'Adult Contemporary');
INSERT INTO Genre(songId, sgenre) VALUES (61, 'Adult Contemporary');
INSERT INTO Genre(songId, sgenre) VALUES (62, 'R&B');
INSERT INTO Genre(songId, sgenre) VALUES (62, 'Soul');
INSERT INTO Genre(songId, sgenre) VALUES (63, 'R&B');
INSERT INTO Genre(songId, sgenre) VALUES (63, 'Soul');
INSERT INTO Genre(songId, sgenre) VALUES (64, 'Adult Contemporary');
INSERT INTO Genre(songId, sgenre) VALUES (65, 'Adult Contemporary');
INSERT INTO Genre(songId, sgenre) VALUES (66, 'Indie rock');
INSERT INTO Genre(songId, sgenre) VALUES (66, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (67, 'Pop Rock');
INSERT INTO Genre(songId, sgenre) VALUES (67, 'Indie Rock');
INSERT INTO Genre(songId, sgenre) VALUES (67, 'Alternative Rock');
INSERT INTO Genre(songId, sgenre) VALUES (68, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (69, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (70, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (71, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (72, 'ska Pop');
INSERT INTO Genre(songId, sgenre) VALUES (73, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (74, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (75, 'Pop');
INSERT INTO Genre(songId, sgenre) VALUES (75, 'Romantic');
INSERT INTO Genre(songId, sgenre) VALUES (76, 'Indipop');
INSERT INTO Genre(songId, sgenre) VALUES (76, 'Dance');
INSERT INTO Genre(songId, sgenre) VALUES (77, 'Indian pop music');
INSERT INTO Genre(songId, sgenre) VALUES (78, 'Romantic');
INSERT INTO Genre(songId, sgenre) VALUES (79, 'Romantic');
INSERT INTO Genre(songId, sgenre) VALUES (80, 'Indian pop Music');
INSERT INTO Genre(songId, sgenre) VALUES (81, 'Indie Rock Music');
INSERT INTO Genre(songId, sgenre) VALUES (82, 'Romantic');
INSERT INTO Genre(songId, sgenre) VALUES (83, 'Dubstep');
INSERT INTO Genre(songId, sgenre) VALUES (84, 'Dubstep');
INSERT INTO Genre(songId, sgenre) VALUES (85, 'Acoustic');
INSERT INTO Genre(songId, sgenre) VALUES (85, 'Romantic');
INSERT INTO Genre(songId, sgenre) VALUES (86, 'Rock');
INSERT INTO Genre(songId, sgenre) VALUES (87, 'Rock');
INSERT INTO Genre(songId, sgenre) VALUES (88, 'rock');
INSERT INTO Genre(songId, sgenre) VALUES (89, 'Rock');
INSERT INTO Genre(songId, sgenre) VALUES (90, 'Rock');
INSERT INTO Genre(songId, sgenre) VALUES (91, 'Rock');
INSERT INTO Genre(songId, sgenre) VALUES (92, 'Rock Punjabi');
INSERT INTO Genre(songId, sgenre) VALUES (93, 'Rock Punjabi');
INSERT INTO Genre(songId, sgenre) VALUES (94, 'Rock Punjabi');
INSERT INTO Genre(songId, sgenre) VALUES (95, 'Romantic');
INSERT INTO Genre(songId, sgenre) VALUES (96, 'Rock Punjabi');
INSERT INTO Genre(songId, sgenre) VALUES (97, 'Rock');
INSERT INTO Genre(songId, sgenre) VALUES (98, 'Rock');
INSERT INTO Genre(songId, sgenre) VALUES (99, 'Indiepop');
INSERT INTO Genre(songId, sgenre) VALUES (100, 'Latin pop');
INSERT INTO Genre(songId, sgenre) VALUES (101, 'Latin pop');
INSERT INTO Genre(songId, sgenre) VALUES (102, 'Latin pop');
INSERT INTO Genre(songId, sgenre) VALUES (103, 'Latin pop');
INSERT INTO Genre(songId, sgenre) VALUES (104, 'Latin pop');
INSERT INTO Genre(songId, sgenre) VALUES (105, 'Dance/Electronic');
INSERT INTO Genre(songId, sgenre) VALUES (106, 'Latin pop');
INSERT INTO Genre(songId, sgenre) VALUES (107, 'Latin pop');
INSERT INTO Genre(songId, sgenre) VALUES (108, 'Latin pop');
INSERT INTO Genre(songId, sgenre) VALUES (109, 'Latin pop');
INSERT INTO Genre(songId, sgenre) VALUES (110, 'Latin pop');
