INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (1, '1', 'AtlanticAsylum', TO_DATE('12/07/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (1, '2', 'AtlanticAsylum', TO_DATE('12/07/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (1, '3', 'AtlanticAsylum', TO_DATE('12/07/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (2, '4', 'EpicSyco', TO_DATE('01/08/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (2, '2', 'EpicSyco', TO_DATE('01/08/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (3, '5', 'Disruptor', TO_DATE('07/02/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (3, '6', 'Disruptor', TO_DATE('07/02/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (4, '5', 'Disruptor', TO_DATE('29/07/2016', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (4, '7', 'Disruptor', TO_DATE('29/07/2016', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (5, '1', 'Atlantic UK', TO_DATE('10/05/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (5, '8', 'Atlantic UK', TO_DATE('10/05/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (6, '9', 'Republic', TO_DATE('07/08/2015', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (7, '9', 'Republic', TO_DATE('26/02/2016', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (7, '10', 'Republic', TO_DATE('26/02/2016', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (8, '9', 'Republic', TO_DATE('22/07/2016', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (8, '11', 'Republic', TO_DATE('22/07/2016', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (8, '12', 'Republic', TO_DATE('22/07/2016', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (9, '12', 'Interscope', TO_DATE('23/02/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (9, '13', 'Interscope', TO_DATE('23/02/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (10, '13', 'Def Jam', TO_DATE('26/07/2016', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (11, '14', 'Universal Music', TO_DATE('13/01/2003', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (12, '15', 'Columbia', TO_DATE('12/08/2013', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (12, '16', 'Columbia', TO_DATE('12/08/2013', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (13, '16', 'Capitol', TO_DATE('17/12/2013', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (13, '17', 'Capitol', TO_DATE('17/12/2013', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (14, '15', 'Aware', TO_DATE('12/09/2006', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (15, '18', 'Erskine', TO_DATE('31/10/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (16, '18', 'Erskine', TO_DATE('07/08/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (17, '19', 'Columbia', TO_DATE('21/05/1998', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (18, '20', 'Parlophone', TO_DATE('04/12/1964', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (19, '20', 'Apple', TO_DATE('26/08/1968', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (20, '21', 'Albert', TO_DATE('25/07/1980', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (21, '21', 'Albert', TO_DATE('25/07/1980', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (22, '21', 'Albert', TO_DATE('25/07/1980', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (23, '22', 'Reprise', TO_DATE('12/09/2006', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (24, '23', 'Island', TO_DATE('23/10/2012', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (25, '15', 'Columbia', TO_DATE('17/11/2009', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (26, '20', 'Capitol', TO_DATE('06/08/1965', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (27, '5', 'Disruptor', TO_DATE('13/01/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (28, '24', 'Creations', TO_DATE('13/01/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (29, '25', 'Island', TO_DATE('23/02/1993', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (30, '5', 'Columbia', TO_DATE('08/11/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (31, '26', 'Interscope', TO_DATE('08/05/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (32, '27', 'Columbia', TO_DATE('02/02/1994', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (33, '28', 'RCA', TO_DATE('31/05/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (34, '29', 'TVT', TO_DATE('11/10/2005', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (35, '5', 'Columbia', TO_DATE('16/11/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (36, '30', 'Interscope', TO_DATE('21/09/1995', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (37, '31', 'RCA Victor', TO_DATE('15/02/1974', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (38, '5', 'Columbia', TO_DATE('16/03/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (39, '32', 'Columbia', TO_DATE('30/11/2016', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (40, '33', 'Visionary', TO_DATE('13/05/2016', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (41, '34', 'Capitol', TO_DATE('29/09/2015', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (42, '35', 'RCA', TO_DATE('12/04/1971', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (43, '36', 'RCA', TO_DATE('29/11/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (43, '28', 'RCA', TO_DATE('29/11/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (44, '36', 'Columbia', TO_DATE('10/11/2014', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (44, '37', 'Columbia', TO_DATE('10/11/2014', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (45, '38', 'Hut', TO_DATE('16/06/1997', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (46, '38', 'Hut', TO_DATE('24/11/1997', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (47, '15', 'Aware', TO_DATE('12/09/2006', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (48, '5', 'Columbia', TO_DATE('29/03/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (49, '15', 'Aware', TO_DATE('12/09/2006', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (50, '15', 'Aware', TO_DATE('12/09/2006', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (51, '25', 'Island', TO_DATE('01/03/1993', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (52, '5', 'Columbia', TO_DATE('31/05/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (52, '39', 'Columbia', TO_DATE('31/05/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (53, '26', 'Interscope', TO_DATE('08/05/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (54, '26', 'Interscope', TO_DATE('08/05/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (55, '40', 'STMPD', TO_DATE('26/07/2016', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (55, '39', 'STMPD', TO_DATE('26/07/2016', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (56, '38', 'Hut', TO_DATE('24/11/1997', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (57, '18', 'Erskine', TO_DATE('07/08/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (58, '18', 'Erskine', TO_DATE('07/08/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (59, '15', 'Aware', TO_DATE('01/07/2008', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (60, '15', 'Aware', TO_DATE('09/11/1999', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (61, '15', 'Aware', TO_DATE('01/07/2008', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (62, '15', 'Aware', TO_DATE('01/07/2008', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (63, '15', 'Aware', TO_DATE('15/11/2006', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (64, '15', 'Aware', TO_DATE('20/08/2008', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (65, '15', 'Aware', TO_DATE('21/11/2008', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (66, '26', 'Interscope', TO_DATE('21/02/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (67, '26', 'Interscope', TO_DATE('08/05/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (68, '2', 'EpicSyco', TO_DATE('21/06/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (69, '2', 'EpicSyco', TO_DATE('05/09/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (70, '2', 'EpicSyco', TO_DATE('04/10/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (71, '2', 'EpicSyco', TO_DATE('15/11/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (72, '2', 'EpicSyco', TO_DATE('11/10/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (73, '18', 'Erskine', TO_DATE('11/10/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (74, '18', 'Erskine', TO_DATE('16/11/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (75, '41', 'T-series', TO_DATE('24/01/2014', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (76, '41', 'T-series', TO_DATE('24/01/2014', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (77, '42', 'Sony Music India', TO_DATE('08/11/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (78, '43', 'T-series', TO_DATE('23/08/2015', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (79, '43', 'T-series', TO_DATE('23/08/2015', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (80, '44', 'T-series', TO_DATE('30/01/2014', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (81, '44', 'T-series', TO_DATE('30/01/2014', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (82, '44', 'Sony Music Entertainment', TO_DATE('15/11/2015', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (83, '45', 'Su Real', TO_DATE('24/12/2014', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (84, '45', 'Su Real', TO_DATE('24/12/2014', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (85, '46', 'Junglee Music', TO_DATE('25/06/2014', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (86, '47', 'MTV', TO_DATE('09/06/2015', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (87, '47', 'MTV', TO_DATE('08/05/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (88, '47', 'MTV', TO_DATE('08/05/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (89, '47', 'MTV', TO_DATE('08/06/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (90, '47', 'MTV', TO_DATE('21/07/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (91, '47', 'MTV', TO_DATE('07/06/2015', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (92, '48', 'T-series', TO_DATE('26/08/2014', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (93, '48', 'T-series', TO_DATE('28/08/2014', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (94, '49', 'T-series', TO_DATE('03/03/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (95, '49', 'T-series', TO_DATE('07/07/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (96, '50', 'T-series', TO_DATE('05/08/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (97, '50', 'T-series', TO_DATE('16/11/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (98, '51', 'T-series', TO_DATE('02/06/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (99, '51', 'T-series', TO_DATE('14/10/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (100, '52', 'Universal Latin', TO_DATE('12/01/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (100, '53', 'Universal Latin', TO_DATE('12/01/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (100, '54', 'Universal Latin', TO_DATE('12/01/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (101, '52', 'Universal Latin', TO_DATE('17/11/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (102, '52', 'Universal Latin', TO_DATE('14/06/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (103, '52', 'Universal Latin', TO_DATE('19/10/2018', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (104, '52', 'Universal Latin', TO_DATE('23/01/2019', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (105, '55', 'Columbia', TO_DATE('30/06/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (105, '56', 'Columbia', TO_DATE('30/06/2017', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (106, '57', 'Epic', TO_DATE('12/04/2005', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (107, '57', 'Epic', TO_DATE('02/07/2005', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (108, '57', 'Epic', TO_DATE('19/01/2006', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (109, '57', 'Epic', TO_DATE('14/05/2007', 'DD/MM/YYYY'));
INSERT INTO SongBy(songId, artistId, label, releaseDate) VALUES (110, '57', 'Epic', TO_DATE('08/05/2005', 'DD/MM/YYYY'));
