INSERT INTO Song(songId, songName, duration, language) VALUES (1, 'South of the Border', 734400, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (2, 'Senorita', 190960, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (3, 'Who Do You Love', 226746, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (4, 'Closer', 244960, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (5, 'I Don''t Care', 788400, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (6, 'Love Myself', 218773, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (7, 'Rock Bottom', 198240, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (8, 'Starving', 181880, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (9, 'Stay', 210090, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (10, 'Scars to Your Beautiful', 230226, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (11, 'Year 3000', 196013, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (12, 'Who You Love', 249933, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (13, 'Dark Horse', 215672, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (14, 'Slow Dancing In A Burning Room', 242000, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (15, 'Kiwi', 176386, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (16, 'Two Ghosts', 229813, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (17, 'Digging My Potato', 0, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (18, 'Eight Days A Week', 0, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (19, 'Hey Jude', 0, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (20, 'Back In Black', 255493, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (21, 'Shoot To Thrill', 328200, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (22, 'Rock And Roll Ain''t Noise Pollution', 266040, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (23, 'Welcome to Black Parade', 210000, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (24, 'Miss Atomic Bomb', 293506, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (25, 'Edge Of Desire', 332066, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (26, 'Yesterday', 125666, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (27, 'Paris', 221520, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (28, 'Star Roving', 338869, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (29, 'Linger', 274706, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (30, 'Push My Luck', 181844, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (31, 'Whatever It Takes', 201240, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (32, 'Streets Of Philadelphia', 195080, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (33, 'DREAM', 168346, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (34, 'The Memory Will Never Die', 263653, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (35, 'Beach House', 206120, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (36, 'Not Just A Girl', 262813, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (37, 'Rebel Rebel', 190666, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (38, 'Everybody Hates Me', 223466, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (39, 'Alive', 210866, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (40, 'All Time Low', 219460, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (41, 'Jackie and Wilson', 223120, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (42, 'Take Me Home, Country Roads', 190160, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (43, 'Nothing Breaks Like a Heart', 217466, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (44, 'Uptown Funk', 269666, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (45, 'Bitter Sweet Symphony', 357266, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (46, 'Lucky Man', 293586, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (47, 'In Repair', 367813, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (48, 'Kills You Slowly', 213333, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (49, 'Gravity', 245826, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (50, 'Dreaming With A Broken Heart', 245746, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (51, 'Dreams', 255106, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (52, 'Call You Mine', 217653, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (53, 'Walking the Wire', 232906, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (54, 'Dancing In The Dark', 233933, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (55, 'In the Name of Love', 195706, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (56, 'Standing In The Right Place', 216693, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (57, 'Sweet Creature', 224866, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (58, 'Sign Of The Times', 340706, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (59, 'Gravity', 245826, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (60, 'Neon', 262106, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (61, 'Neon', 262106, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (62, 'Stop This Train', 285000, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (63, 'Stop This Train', 285000, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (64, 'Everyday I Have The Blues', 254266, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (65, 'Everyday I Have The Blues', 254266, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (66, 'Next to Me', 230288, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (67, 'Yesterday', 205113, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (68, 'Shameless', 219742, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (69, 'Liar', 207038, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (70, 'Cry for Me', 189133, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (71, 'Living Proof', 194440, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (72, 'Easy', 194686, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (73, 'Lights up', 172213, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (74, 'Watermelon Sugar', 174000, 'English');
INSERT INTO Song(songId, songName, duration, language) VALUES (75, 'Kahaan hoon main', 327362, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (76, 'Maahi Ve', 223999, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (77, 'Tera Zikr', 208500, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (78, 'Khwaishein', 310288, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (79, 'Raabta', 297158, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (80, 'Badra Bahaar', 214131, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (81, 'Jugni', 262733, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (82, 'Tu Hi Hai', 199643, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (83, 'Beatific', 240000, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (84, 'I feel love', 254453, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (85, 'Tum Chal Diye', 206329, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (86, 'Choo Lo', 233630, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (87, 'Gustaakh', 184320, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (88, 'Khudi', 297642, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (89, 'Mere Yaar', 286720, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (90, 'Mizaaj', 263509, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (91, 'Dil Mere', 211290, 'Hindi');
INSERT INTO Song(songId, songName, duration, language) VALUES (92, 'Love Dose', 224444, 'Punjabi');
INSERT INTO Song(songId, songName, duration, language) VALUES (93, 'One Thousand Miles', 283074, 'Punjabi');
INSERT INTO Song(songId, songName, duration, language) VALUES (94, 'Kalesh', 173662, 'Punjabi');
INSERT INTO Song(songId, songName, duration, language) VALUES (95, 'Main Teri Ho Gayi', 173662, 'Punjabi');
INSERT INTO Song(songId, songName, duration, language) VALUES (96, 'Ishare tere', 259685, 'Punjabi');
INSERT INTO Song(songId, songName, duration, language) VALUES (97, 'Lahore', 197390, 'Punjabi');
INSERT INTO Song(songId, songName, duration, language) VALUES (98, 'Belly Ring', 197640, 'Punjabi');
INSERT INTO Song(songId, songName, duration, language) VALUES (99, 'Hawa Hawa', 171987, 'Punjabi');
INSERT INTO Song(songId, songName, duration, language) VALUES (100, 'Despacito', 228826, 'Spanish');
INSERT INTO Song(songId, songName, duration, language) VALUES (101, 'Échame la Culpa', 173800, 'Spanish');
INSERT INTO Song(songId, songName, duration, language) VALUES (102, 'Calypso', 200973, 'Spanish');
INSERT INTO Song(songId, songName, duration, language) VALUES (103, 'Imposible', 164533, 'Spanish');
INSERT INTO Song(songId, songName, duration, language) VALUES (104, 'Sola', 243560, 'Spanish');
INSERT INTO Song(songId, songName, duration, language) VALUES (105, 'Mi Gente', 185040, 'Spanish');
INSERT INTO Song(songId, songName, duration, language) VALUES (106, 'La Tortura', 212893, 'Spanish');
INSERT INTO Song(songId, songName, duration, language) VALUES (107, 'No', 260000, 'Spanish');
INSERT INTO Song(songId, songName, duration, language) VALUES (108, 'Día de Enero', 135511, 'Spanish');
INSERT INTO Song(songId, songName, duration, language) VALUES (109, 'Las de la Intuición', 220666, 'Spanish');
INSERT INTO Song(songId, songName, duration, language) VALUES (110, 'Lo Imprescindible', 234866, 'Spanish');
